-dontwarn org.slf4j.impl.StaticLoggerBinder
-keep, allowobfuscation, allowshrinking interface retrofit2.Call
-keep, allowobfuscation, allowshrinking class retrofit2.Response
-keep, allowobfuscation, allowshrinking class kotlin.coroutines.Continuation